// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  embed_section: dynamic(() => import("./EmbedSection")),
  split_image_text: dynamic(() => import("./SplitImageText")),
  text_slice: dynamic(() => import("./TextSlice")),
};
